### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [Belzee10/provoke-array#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by Belzee10** [comment]
Hey @geopic sorry for the delay, I was so busy the last days. Feel free to open a PR adding TS type declarations.

**Comment by geopic** [comment]
Sure thing, I'll get started on it soon then.
